# Generated by Django 5.1.7 on 2025-04-02 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='phone_number',
        ),
    ]
