services:
  db:
    image: postgres:17.3-alpine3.21
    container_name: school2-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: school2_db
    volumes:
      - school2_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: school2-backend
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: school2_db
      DATABASE_HOST: school2-db
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app/backend
      - ./insightface_models:/root/.insightface/models
      - ./.env.school2:/app/backend/.env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: school2-frontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
      VITE_API_URL: http://localhost:8001
    ports:
      - "5174:5173"
    volumes:
      - ./frontend:/app
      - school2_node_modules_frontend:/app/node_modules
    depends_on:
      - backend

volumes:
  school2_node_modules_frontend:
  school2_postgres_data: