services:
  db:
    image: postgres:17.3-alpine3.21
    container_name: attendai-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      network: host  # This makes the build process use the host network
    container_name: attendai-backend
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./backend
        target: /app/backend
        consistency: delegated
      - type: bind
        source: ./insightface_models
        target: /root/.insightface/models
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      network: host
    container_name: attendai-frontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "5173:5173"
    volumes:
      - type: bind
        source: ./frontend
        target: /app
        consistency: delegated
      - node_modules_frontend:/app/node_modules
    depends_on:
      - backend

volumes:
  node_modules_frontend:
  postgres_data:
