services:
  db:
    image: postgres:17.3-alpine3.21
    container_name: school1-db
    ports:
      - "5434:5432"  
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: school1_db
    volumes:
      - school1_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: school1-backend
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: school1_db
      DATABASE_HOST: school1-db
    ports:
      - "8002:8000" 
    volumes:
      - ./backend:/app/backend
      - ./insightface_models:/root/.insightface/models
      - ./.env.school1:/app/backend/.env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: school1-frontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
      VITE_API_URL: http://localhost:8002  # Changed from 8000
    ports:
      - "5175:5173"  # Changed from 5173
    volumes:
      - ./frontend:/app
      - school1_node_modules_frontend:/app/node_modules
    depends_on:
      - backend

volumes:
  school1_node_modules_frontend:
  school1_postgres_data: