# Generated by Django 5.1.7 on 2025-04-05 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facial_recognition', '0005_delete_attendancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewface',
            name='face_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_face', to='facial_recognition.faceimage'),
        ),
    ]
