# Generated by Django 5.1.7 on 2025-04-03 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('school_data', '0002_remove_parentprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_data.studentprofile'),
        ),
    ]
