# Generated by Django 5.1.7 on 2025-04-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routineentry',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='routineentry',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='routineentry',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='routineentry',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')]),
        ),
    ]
