# Generated by Django 5.1.7 on 2025-04-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_remove_routineentry_time_slot_routineentry_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routineentry',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='routineentry',
            name='start_time',
        ),
        migrations.AddField(
            model_name='routineentry',
            name='time_slot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='routineentry',
            name='day_of_week',
            field=models.IntegerField(),
        ),
    ]
